In [1]:
import numpy as np

In [6]:
cube = np.zeros((6, 4),dtype='i')
cube[0][3]=5
print(cube)

[[0 0 0 5]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [12]:
def InitCube():
# 初始化函数，新建四维数组并从键盘输入魔方的初始状态
    print("请将您的魔方任选一面对着自己并按照前、右、后、左、上、下的顺序以及每一面按照从上到下从左到右的顺序输入颜色")
    # 先不搞键盘输入，直接自定义
    # 0-5分别表示橙蓝红绿黄白六种颜色
    
    # 前
    cube[0][0]=0
    cube[0][1]=0
    cube[0][2]=0
    cube[0][3]=0
    
    #右
    cube[1][0]=1
    cube[1][1]=1
    cube[1][2]=1
    cube[1][3]=1
    
    #后
    cube[2][0]=2
    cube[2][1]=2
    cube[2][2]=2
    cube[2][3]=2
    
    #左
    cube[3][0]=3
    cube[3][1]=3
    cube[3][2]=3
    cube[3][3]=3
    
    #上
    cube[4][0]=4
    cube[4][1]=4
    cube[4][2]=4
    cube[4][3]=4
    
    #下
    cube[5][0]=5
    cube[5][1]=5
    cube[5][2]=5
    cube[5][3]=5

In [ ]:
def FirstStep():
    # 还原魔方的第一步
    


In [13]:
def Rotate(direction):
    # 对魔方进行旋转操作，direction为0、1、2、3分别表示左、上、右、下
    if(direction==0):#"左"
        
        a=cube[0][0]
        b=cube[0][1]
        
        #前
        cube[0][0]=cube[1][0]
        cube[0][1]=cube[1][1]

        #右
        cube[1][0]=cube[2][0]
        cube[1][1]=cube[2][1]

        #后
        cube[2][0]=cube[3][0]
        cube[2][1]=cube[3][1]

        #左
        cube[3][0]=a
        cube[3][1]=b
        
        #上
        a=cube[4][0]
        cube[4][0]=cube[4][1]
        cube[4][1]=cube[4][2]
        cube[4][2]=cube[4][3]
        cube[4][3]=cube[4][0]
        
    if(direction==1):#“上”
        
        a=cube[0][0]
        b=cube[0][1]
        
        #前
        cube[0][0]=cube[1][0]
        cube[0][1]=cube[1][1]

        #右
        cube[1][0]=cube[2][0]
        cube[1][1]=cube[2][1]

        #后
        cube[2][0]=cube[3][0]
        cube[2][1]=cube[3][1]

        #左
        cube[3][0]=a
        cube[3][1]=b

In [14]:
InitCube()
Rotate(0)
print(cube)

请将您的魔方任选一面对着自己并按照前、右、后、左、上、下的顺序以及每一面按照从上到下从左到右的顺序输入颜色
[[1 1 0 0]
 [2 2 1 1]
 [3 3 2 2]
 [0 0 3 3]
 [4 4 4 4]
 [5 5 5 5]]


In [4]:
def main():
# 主函数
    cube = np.zeros((2, 2, 2, 6),dtype='i')
    InitCube()
    FirstStep()
    SecondStep()
    ThirdStep()

In [ ]:
int SecondStep()//还原魔方的第二步
int ThirdStep()//还原魔方的第三步
int PrintCube()//将魔方当前的状态打印出来
int JudgeSolve()//检验魔方是否已经复原