In [2]:
import numpy as np

In [7]:
cube = np.zeros((6, 4),dtype='i')
InitCube()
cube[0][3]=5
print(cube)

请将您的魔方任选一面对着自己并按照前、右、后、左、上、下的顺序以及每一面按照从上到下从左到右的顺序输入颜色
[[0 0 0 5]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]


In [15]:
def JudgeSolve():#检验魔方是否已经复原
    judge0=False
    judge1=False
    judge2=False
    judge3=False
    judge4=False
    judge5=False
    if(cube[0][0]==cube[0][1] and cube[0][1]==cube[0][2] and cube[0][2]==cube[0][3]):
        judge0=True
    if(cube[1][0]==cube[1][1] and cube[1][1]==cube[1][2] and cube[1][2]==cube[1][3]):
        judge1=True
    if(cube[2][0]==cube[2][1] and cube[2][1]==cube[2][2] and cube[2][2]==cube[2][3]):
        judge2=True
    if(cube[3][0]==cube[3][1] and cube[3][1]==cube[3][2] and cube[3][2]==cube[3][3]):
        judge3=True
    if(cube[4][0]==cube[4][1] and cube[4][1]==cube[4][2] and cube[4][2]==cube[4][3]):
        judge4=True
    if(cube[5][0]==cube[5][1] and cube[5][1]==cube[5][2] and cube[5][2]==cube[5][3]):
        judge5=True
    if(judge0==True and judge1==True and judge2==True and judge3==True and judge4==True and judge5==True):
        return 1
    else:
        return 0

In [6]:
def InitCube():
# 初始化函数，新建四维数组并从键盘输入魔方的初始状态
    print("请将您的魔方任选一面对着自己并按照前、右、后、左、上、下的顺序以及每一面按照从上到下从左到右的顺序输入颜色")
    # 先不搞键盘输入，直接自定义
    # 0-5分别表示橙蓝红绿黄白六种颜色
    
    # 前
    cube[0][0]=0
    cube[0][1]=0
    cube[0][2]=0
    cube[0][3]=0
    
    #右
    cube[1][0]=1
    cube[1][1]=1
    cube[1][2]=1
    cube[1][3]=1
    
    #后
    cube[2][0]=2
    cube[2][1]=2
    cube[2][2]=2
    cube[2][3]=2
    
    #左
    cube[3][0]=3
    cube[3][1]=3
    cube[3][2]=3
    cube[3][3]=3
    
    #上
    cube[4][0]=4
    cube[4][1]=4
    cube[4][2]=4
    cube[4][3]=4
    
    #下
    cube[5][0]=5
    cube[5][1]=5
    cube[5][2]=5
    cube[5][3]=5

In [ ]:
def FirstStep():
    # 还原魔方的第一步
    # 随便找一个白色的块
    for i in range(6):
        for j in range(4):
            if(cube[i][j])==0):
                #找到该该白色块将其放到下面的左上角即cube[5][0]
                cube
                

In [ ]:
def Rotate(direction,step):
    #direction可以取0、1、2、3分别代表顺时针旋转上层、下层、左层、右层
    if(direction==0):
        if(step==1):
            a=cube[4][0]
            cube[4][0]=cube[4][2]
            cube[4][2]=cube[4][3]
            cube[4][3]=cube[4][1]
            cube[4][1]=a
            a=cube[2][1]
            cube[2][1]=cube[3][1]
            cube[3][1]=cube[0][1]
            cube[0][1]=cube[1][1]
            cube[1][1]=a
            a=cube[2][0]
            cube[2][0]=cube[3][0]
            cube[3][0]=cube[0][0]
            cube[0][0]=cube[1][0]
            cube[1][0]=a
        if(step==2):
            a=cube[4][0]
            cube[4][0]=cube[4][3]
            cube[4][3]=a
            a=cube[4][1]
            cube[4][1]=cube[4][2]
            cube[4][2]=a
            a=cube[2][1]
            cube[2][1]=cube[1][0]
            cube[0][1]=a
            a=cube[2][0]
            cube[2][0]=cube[0][0]
            cube[0][0]=a
            a=cube[1][1]
            cube[1][1]=cube[3][1]
            cube[3][1]=a
            a=cube[1][0]
            cube[1][0]=cube[3][0]
            cube[3][0]=a
        if(step==2): 
            a=cube[4][0]
            cube[4][0]=cube1[4][1]
            cube[4][1]=cube[4][3]
            cube[4][3]=cube[4][2]
            cube[4][2]=a
            a=cube[2][1]
            cube[2][1]=cube[1][1]
            cube[1][1]=cube[0][1]
            cube[0][1]=cube[3][1]
            cube[3][1]=a
            a=cube[2][0]
            cube[2][0]=cube[1][0]
            cube[1][0]=cube[0][0]
            cube[0][0]=cube[3][0]
            cube[3][0]=a
    if(direction==1):
        if(step==1):
            a=cube[5][0]
            cube[5][0]=cube[5][2]
            cube[5][2]=cube[5][3]
            cube[5][3]=cube1[5][1]
            cube[5][1]=a
            a=cube[0][2]
            cube[0][2]=cube[3][3]
            cube[3][3]=cube[2][2]
            cube[2][2]=cube[1][2]
            cube[1][2]=a
            a=cube[0][3]
            cube[0][3]=cube[3][2]
            cube[3][2]=cube[2][3]
            cube[2][3]=cube[1][3]
            cube[1][3]=a
        if(step==2):
            a=cube[5][0]
            cube[5][0]=cube[5][3]
            cube[5][3]=a
            a=cube[5][1]
            cube[5][1]=cube[5][2]
            cube[5][2]=a
            a=cube[0][2]
            cube[0][2]=cube[2][2]
            cube[2][2]=a
            a=cube[0][3]
            cube[0][3]=cube[2][3]
            cube[2][3]=a
            a=cube[1][2]
            cube[1][2]=cube[3][3]
            cube[3][3]=a
            a=cube[1][3]
            cube[1][3]=cube[3][2]
            cube[3][2]=a
        if(step==3):
            a=cube[5][0]
            cube[5][0]=cube[5][1]
            cube[5][1]=cube[5][3]
            cube[5][3]=cube[5][2]
            cube[5][2]=a
            a=cube[0][2]
            cube[0][2]=cube[1][2]
            cube[1][2]=cube[2][2]
            cube[2][2]=cube[3][3]
            cube[3][3]=a
            a=cube[0][3]
            cube[0][3]=cube[1][3]
            cube[1][3]=cube[2][3]
            cube[2][3]=cube[3][2]
            cube[3][2]=a
    if(direction==2):
        if(step==1):
            a=cube[3][0]
            cube[3][0]=cube[3][2]
            cube[3][2]=cube[3][3]
            cube[3][3]=cube[3][1]
            cube[3][1]=a
            a=cube[4][0]
            cube[4][0]=cube[2][3]
            cube[2][3]=cube[5][0]
            cube[5][0]=cube[0][0]
            cube[0][0]=a
            a=cube[4][2]
            cube[4][2]=cube[2][1]
            cube[2][1]=cube[5][2]
            cube[5][2]=cube[0][2]
            cube[0][2]=a
        if(step==2):
            a=cube[3][0]
            cube[3][0]=cube[3][3]
            cube[3][3]=a
            a=cube[3][1]
            cube[3][1]=cube[3][2]
            cube[3][2]=a
            a=cube[4][0]
            cube[4][0]=cube[5][0]
            cube[5][0]=a
            a=cube[4][2]
            cube[4][2]=cube[5][2]
            cube[5][2]=a
            a=cube[0][0]
            cube[0][0]=cube[2][3]
            cube[2][3]=a
            a=cube[0][2]
            cube[0][2]=cube[2][1]
            cube[2][1]=a
        if(step==3):
            a=cube[3][0]
            cube[3][0]=cube[3][1]
            cube[3][1]=cube[3][3]
            cube[3][3]=cube[3][2]
            cube[3][2]=a
            a=cube[4][0]
            cube[4][0]=cube[0][0]
            cube[0][0]=cube[5][0]
            cube[5][0]=cube[2][3]
            cube[2][3]=a
            a=cube[4][2]
            cube[4][2]=cube[0][2]
            cube[0][2]=cube[5][2]
            cube[5][2]=cube[2][1]
            cube[2][1]=a
    if(direction==3):
        if(step==1):
            a=cube[1][0]
            cube[1][0]=cube[1][2]
            cube[1][2]=cube[1][3]
            cube[1][3]=cube[1][1]
            cube[1][1]=a
            a=cube[4][3]
            cube[4][3]=cube[0][3]
            cube[0][3]=cube[5][3]
            cube[5][3]=cube[2][0]
            cube[2][0]=a
            a=cube[4][1]
            cube[4][1]=cube[0][1]
            cube[0][1]=cube[5][1]
            cube[5][1]=cube[2][2]
            cube[2][2]=a
        if(step==2):
            a=cube[1][0]
            cube[1][0]=cube[1][3]
            cube[1][3]=a
            a=cube[1][1]
            cube[1][1]=cube[1][2]
            cube[1][2]=a
            a=cube[4][3]
            cube[4][3]=cube[5][3]
            cube[5][3]=a
            a=cube[4][1]
            cube[4][1]=cube[5][1]
            cube[5][1]=a
            a=cube[2][0]
            cube[2][0]=cube[0][3]
            cube[0][3]=a
            a=cube[2][2]
            cube[2][2]=cube[0][1]
            cube[0][1]=a
        if(step==3):
            a=cube[1][0]
            cube[1][0]=cube[1][1]
            cube[1][1]=cube[1][3]
            cube[1][3]=cube[1][2]
            cube[1][2]=a
            a=cube[4][3]
            cube[4][3]=cube[2][0]
            cube[2][0]=cube[5][3]
            cube[5][3]=cube[0][3]
            cube[0][1]=a
            a=cube[4][1]
            cube[4][1]=cube[2][2]
            cube[2][2]=cube[5][1]
            cube[5][1]=cube[0][1]
            cube[0][1]=a

In [ ]:
'''
def subRotate(cube0,cube1,cube2,cube3,cube4,cube5,cube6,cube7,cube8,cube9,cube10,cube11,step):
    if(step==1):
        a=cube0
        cube0=cube2
        cube2=cube3
        cube3=cube1
        cube1=a
        a=cube4
        cube4=cube10
        cube10=cube8
        cube8=cube6
        cube6=a
        a=cube5
        cube5=cube11
        cube11=cube9
        cube9=cube7
        cube7=a
    if(step==2):
        a=cube0
        cube0=cube3
        cube3=a
        a=cube1
        cube1=cube2
        cube2=a
        a=cube4
        cube4=cube8
        cube8=a
        a=cube5
        cube5=cube9
        cube9=a
        a=cube6
        cube6=cube10
        cube10=a
        a=cube7
        cube7=cube11
        cube11=a
    if(step==3):
        a=cube0
        cube0=cube1
        cube1=cube3
        cube3=cube2
        cube2=a
        a=cube4
        cube4=cube6
        cube6=cube8
        cube8=cube10
        cube10=a
        a=cube5
        cube5=cube7
        cube7=cube9
        cube9=cube11
        cube11=a
'''

In [13]:
'''
#左上右下旋转函数，以弃用

def Rotate(direction):
    # 对魔方进行旋转操作，direction为0、1、2、3分别表示左、上、右、下
    
    if(direction==0):#"左"
        
        a=cube[0][0]
        b=cube[0][1]
        
        #前
        cube[0][0]=cube[1][0]
        cube[0][1]=cube[1][1]

        #右
        cube[1][0]=cube[2][0]
        cube[1][1]=cube[2][1]

        #后
        cube[2][0]=cube[3][0]
        cube[2][1]=cube[3][1]

        #左
        cube[3][0]=a
        cube[3][1]=b
        
        #上
        a=cube[4][0]
        cube[4][0]=cube[4][2]
        cube[4][2]=cube[4][3]
        cube[4][3]=cube[4][1]
        cube[4][1]=a
        
    if(direction==1):#“上”
        
        a=cube[0][1]
        b=cube[0][3]
        
        #前
        cube[0][1]=cube[5][1]
        cube[0][3]=cube[5][3]

        #下
        cube[5][1]=cube[2][2]
        cube[5][3]=cube[2][0]

        #后
        cube[2][0]=cube[4][3]
        cube[2][2]=cube[4][1]

        #上
        cube[4][1]=a
        cube[4][3]=b
        
        #右
        a=cube[1][0]
        cube[1][0]=cube[1][2]
        cube[1][2]=cube[1][3]
        cube[1][3]=cube[1][1]
        cube[1][1]=a
        
    if(direction==2):#“右”
        
        a=cube[0][0]
        b=cube[0][1]
        
        #前
        cube[0][0]=cube[3][0]
        cube[0][1]=cube[3][1]

        #左
        cube[3][0]=cube[2][0]
        cube[3][1]=cube[2][1]

        #后
        cube[2][0]=cube[1][0]
        cube[2][1]=cube[1][1]

        #右
        cube[1][0]=a
        cube[1][1]=b
        
        #上
        a=cube[4][0]
        cube[4][0]=cube[4][1]
        cube[4][1]=cube[4][3]
        cube[4][3]=cube[4][2]
        cube[4][2]=a
        
    if(direction==1):#“下”
        
        a=cube[0][1]
        b=cube[0][3]
        
        #前
        cube[0][1]=cube[4][1]
        cube[0][3]=cube[4][3]

        #上
        cube[4][1]=cube[2][2]
        cube[4][3]=cube[2][0]

        #后
        cube[2][0]=cube[5][3]
        cube[2][2]=cube[5][1]

        #下
        cube[5][1]=a
        cube[5][3]=b
        
        #右
        a=cube[1][0]
        cube[1][0]=cube[1][1]
        cube[1][1]=cube[1][3]
        cube[1][3]=cube[1][2]
        cube[1][2]=a
    '''

In [14]:
InitCube()
Rotate(0)
print(cube)

请将您的魔方任选一面对着自己并按照前、右、后、左、上、下的顺序以及每一面按照从上到下从左到右的顺序输入颜色
[[1 1 0 0]
 [2 2 1 1]
 [3 3 2 2]
 [0 0 3 3]
 [4 4 4 4]
 [5 5 5 5]]


In [4]:
def main():
# 主函数
    cube = np.zeros((2, 2, 2, 6),dtype='i')
    InitCube()
    FirstStep()
    SecondStep()
    ThirdStep()

In [ ]:
int SecondStep()//还原魔方的第二步
int ThirdStep()//还原魔方的第三步
int PrintCube()//将魔方当前的状态打印出来