In [1]:
import numpy as np

In [8]:
cube = np.zeros((2, 2, 2, 6),dtype='i')
cube[0][1][0][5]=5
print(cube)

[[[[0 0 0 0 0 0]
   [0 0 0 0 0 0]]

  [[0 0 0 0 0 5]
   [0 0 0 0 0 0]]]


 [[[0 0 0 0 0 0]
   [0 0 0 0 0 0]]

  [[0 0 0 0 0 0]
   [0 0 0 0 0 0]]]]


In [5]:
def InitCube():
# 初始化函数，新建四维数组并从键盘输入魔方的初始状态
    print("请将您的魔方任选一面对着自己并按照前、右、后、左、上、下的顺序以及每一面按照从上到下从左到右的顺序输入颜色")
    # 先不搞键盘输入，直接自定义
    # 0-5分别表示橙蓝红绿黄白六种颜色
    
    # 前
    cube[1][0][1][5]=5 #1
    cube[1][0][0][5]=5 #2
    cube[0][0][0][5]=5 #3
    cube[0][0][1][5]=5 #4
    
    #右
    cube[0][0][0][5]=5 #5
    cube[0][0][0][5]=5 #6    
    cube[0][1][0][5]=5 #7
    cube[0][1][0][5]=5 #8
    
    #后
    cube[0][1][0][5]=5 #9
    cube[0][1][0][5]=5 #10
    cube[0][1][0][5]=5 #11
    cube[0][1][0][5]=5 #12
    
    #左
    cube[0][1][0][5]=5 #13
    cube[0][1][0][5]=5 #14
    cube[0][1][0][5]=5 #15
    cube[0][1][0][5]=5 #16
    
    #上
    cube[0][1][0][5]=5 #17
    cube[0][1][0][5]=5 #18
    cube[0][1][0][5]=5 #19
    cube[0][1][0][5]=5 #20
    
    #下
    cube[0][1][0][5]=5 #21
    cube[0][1][0][5]=5 #22
    cube[0][1][0][5]=5 #23
    cube[0][1][0][5]=5 #24
    
int FirstStep()//还原魔方的第一步
int SecondStep()//还原魔方的第二步
int ThirdStep()//还原魔方的第三步
int Rotate(int direction)//对魔方进行旋转操作，direction为0、1、2、3分别表示左、上、右、下
int PrintCube()//将魔方当前的状态打印出来
int JudgeSolve()//检验魔方是否已经复原

In [7]:
def main():
# 主函数
    cube = np.zeros((2, 2, 2, 6),dtype='i')
    InitCube()
    FirstStep()
    SecondStep()
    ThirdStep()

In [ ]:
main()
